### ISSUE TITLE
Asset Cache Time?

### ISSUE THREAD

**Issue by CRYPTO-GENIK** [sushiswap/assets#198]
## How can we help ?

Pushed new logo to repo but the cloud CDN is still serving the old logo.

Wondering how long it will take to update?

https://res.cloudinary.com/dnz2bkszg/image/fetch/https://raw.githubusercontent.com/sushiswap/assets/master/blockchains/ethereum/assets/0xB6ff96B8A8d214544Ca0dBc9B33f7AD6503eFD32/logo.png

Thanks guys <3 <3

**Comment by jiro-ono** [comment]
Is it better now? Usually takes just a couple of hours.

**Comment by CRYPTO-GENIK** [comment]
Yes, it took a few days but it's good now! Thank you
