### ISSUE TITLE
Missing Onsen Pool Logos

### ISSUE THREAD

**Issue by matthewlilley** [sushiswap/assets#6]
# Missing Onsen Pool Logos

- [x] YETI
- [x] DDX
- [x] UWL
- [x] DOUGH
- [x] DFD
- [x] UOP
- [x] COVER
- [ ] nTrump
- [x] YPIE
- [x] TRU
- [x] zLOT
- [x] ARCH
- [x] DUSD
- [x] BOR
- [x] BCP
- [x] oBTC
- [x] DEFI+L
- [x] SEEN
- [x] mbBASED

**Comment by jiro-ono** [comment]
Add most in #11 

nTRUMP don't think we need anymore since that market is pretty much over now
and UOP is coming up in another PR

**Comment by jiro-ono** [comment]
Added UOP in #18
